name = "TFWW"
mainprefix = "z"
prefix = "tfww"
author = "YonV"

[files]
include = [
    "mod.cpp",
    "README.md",
    "LICENSE",
    "AUTHORS.txt",
    "tfww256.paa",
    "tfwwsub256.paa"
]

[lint.sqf]
enabled = true # Default: true
exclude = [
    "a3/3DEN/UI/macroexecs.inc",
    "macroexecs.inc",
    "initSettings.sqf",
    "a3/ui_f/hpp/defineResincl.inc",
    "a3/ui_f/hpp/defineDIKCodes.inc",
    "a3/ui_f/hpp/defineCommonGrids.inc",
    "a3/ui_f/hpp/defineCommonColors.inc",
    "addons/tfar_setter/functions/fn_setProfile.sqf",
    "addons/tfar_setter/XEH_preInit.sqf",
    "addons/tfar_setter/functions/fn_loadSettings.sqf"
]

[Rapify]
exclude = [
    "macroexecs.inc"
]

[asc]
enabled = true # Default: false
exclude = [
]